name: dice_share
description: Compartilhe jogadas de dados em redes sociais.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.5
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  json_annotation: ^4.5.0
  flutter_polygon_clipper: ^1.0.4
  intl: ^0.17.0
  share_plus: ^4.0.4
  screenshot: ^1.2.3
  path_provider: ^2.0.9
  qr_flutter: ^4.0.0
  mobile_scanner: ^1.1.0
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  icons_launcher: ^1.1.7

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
